### ISSUE TITLE
Did not handle one Norwegian letter correctly

### ISSUE THREAD

**Issue by large** [sjh37/Effortless-.Net-Encryption#1]
Hi! Thank you for a great class!
Simple quick and it has been working fine for me.

One user though responded that his name had changed from "Øystein" to "Oystein", and when I tested it it translated "Øø" to "Oo" in the Strings.Decrypt function.

Other special norwegian letters like ÆÅ or æå works just fine 👍 

Is this a known issue? If not any suggestion to work around it?

**Comment by sjh37** [comment]
Hi. I think this is down to using `UTF8` and not `Unicode`

e.g.
```c#
var input = Encoding.UTF8.GetBytes(data + sharedKey);
```
instead of
```c#
var input = Encoding.Unicode.GetBytes(data + sharedKey);
```

Change all UTF8 to be Unicode and let me know if this works for you.

**Comment by sjh37** [comment]
This has now been fixed. Can you please test with v3.0.1.
This is now using Unicode instead of UTF8, so the semantic version has been increased to show incompatibility with v2 hashes.

**Comment by large** [comment]
Wow, that was quick fixed 👍 
Works like a charm in 3.0.1, good work!
