### ISSUE TITLE
Upgrade to Net Standard?

### ISSUE THREAD

**Issue by brianro** [sjh37/Effortless-.Net-Encryption#4]
Any chance you could upgrade to .Net Standard and re-publish? Seemed to compile fine.

**Comment by keerthirajap** [comment]
I am able to convert this project to .net core.

[https://keerthirajap.github.io/Effortless.Net.Core.Encryption/](https://keerthirajap.github.io/Effortless.Net.Core.Encryption/)

Copyrights to Simon Hughes

**Comment by sjh37** [comment]
This has now been done.
It had to be .Net Standard 2.1 in order to support Diffie Hellman
[NuGet package](https://www.nuget.org/packages/Effortless.Net.Encryption/4.0.0)

**Comment by brianro** [comment]
Awesome - thank you.
