### ISSUE TITLE
Cannot install 4.0.0 in a .NET 4.8 project

### ISSUE THREAD

**Issue by Scott31337** [sjh37/Effortless-.Net-Encryption#5]
Trying to update 3.3.0 to 4.0.0 in a .NET 4.8 project gives the error:

Could not install package 'Effortless.Net.Encryption 4.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by sjh37** [comment]
Hi Scott,
Version 4 targets .Net Standard 2.1 which is not supported by .NET Framework. [Microsoft docs](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1#select-net-standard-version)

.Net standard 2.0 is supported by .NET Framework, but does not include all the crypto functions I need. Therefore, for .NET Framework stick with v3.x. This is no functional difference between v3 and v4. Nothing was added or taken away.
